#!/usr/bin/env bash
#
# Verifies that every commit in a range carries a Developer Certificate of
# Origin sign-off matching its own author, as promised in CONTRIBUTING.md.
#
# Usage:  scripts/check_dco.sh <base-ref> <head-ref>
# In CI:  scripts/check_dco.sh "$BASE_SHA" "$HEAD_SHA"   (see .github/workflows/ci.yml)
#
# Run locally before opening a PR:
#   scripts/check_dco.sh origin/main HEAD
#
# Kept as a standalone script rather than inline YAML so it can be executed and
# tested on a developer machine, not only on a runner.
set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: $0 <base-ref> <head-ref>" >&2
    exit 2
fi

base="$1"
head="$2"

# --no-merges: merge commits are generated by the forge, not authored by a
# contributor, so they carry no sign-off obligation.
commits_file="$(mktemp)"
trap 'rm -f "$commits_file"' EXIT
git rev-list --no-merges "$base".."$head" > "$commits_file"

if [ ! -s "$commits_file" ]; then
    echo "No non-merge commits in $base..$head — nothing to check."
    exit 0
fi

failed=0
while IFS= read -r sha; do
    [ -n "$sha" ] || continue
    author="$(git show -s --format='%an <%ae>' "$sha")"
    subject="$(git show -s --format='%s' "$sha")"
    short="$(git rev-parse --short "$sha")"
    # Only the real trailer block counts. `%(trailers:...)` is git's own trailer
    # parser (the one `git interpret-trailers --parse` uses), so a
    # "Signed-off-by:" quoted in the body, or followed by more prose, is not a
    # sign-off. Git matches the key case-insensitively; `valueonly` leaves just
    # "Name <email>", one per line.
    # -x: the whole value must be the author, not merely contain it.
    # -i: contributors hand-write this line often enough that case should not
    #     be the thing that fails a PR. -F: the author string is data, not a regex.
    if git show -s --format='%(trailers:key=Signed-off-by,valueonly,unfold)' "$sha" \
        | grep -qixF -- "$author"; then
        echo "ok   $short $subject"
    else
        echo "FAIL $short $subject"
        echo "     missing: Signed-off-by: $author"
        failed=1
    fi
done < "$commits_file"

if [ "$failed" -ne 0 ]; then
    cat <<'MSG'

Some commits lack a DCO sign-off matching their author.

  Fix the last commit:  git commit --amend -s
  Fix a whole branch:   git rebase --signoff origin/main

Then force-push the branch. See CONTRIBUTING.md for the full policy.
MSG
    exit 1
fi

echo
echo "All commits carry a matching DCO sign-off."
